name: "build"
on:
  pull_request:

jobs:
  build:
    runs-on: macOS-latest
    timeout-minutes: 5
    steps:
      - uses: actions/checkout@v2
      - run: xcodebuild
      - run: xcodebuild test -scheme SampleTests -sdk iphonesimulator -destination 'platform=iOS Simulator,name=iPhone 8,OS=14.4'
