name: "Build and test"
on: pull_request

jobs:
  build-and-test:
    runs-on: macOS-latest
    steps:
      - uses: actions/checkout@v2
      - run: xcodebuild CODE_SIGN_IDENTITY="" CODE_SIGNING_REQUIRED="NO" CODE_SIGN_ENTITLEMENTS="" CODE_SIGNING_ALLOWED="NO"
      - run: xcodebuild test -scheme SampleTests -sdk iphonesimulator -destination 'platform=iOS Simulator,name=iPhone 8,OS=14.4'
